name: Test

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events but only for the master branch
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt', 'project/**') }}

    - name: tmp
      env:
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        GPG_PRIVATE_KEY: ${{ secrets.GPG_KEY }}
        ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}
      run: |
        echo $OSSRH_USERNAME | openssl aes-256-cbc -md sha512 -e -a -pass pass:${ENCRYPTION_PASSWORD}
        echo '-'
        echo $OSSRH_PASSWORD | openssl aes-256-cbc -md sha512 -e -a -pass pass:${ENCRYPTION_PASSWORD}
        echo '-'
        echo $GPG_PASSPHRASE | openssl aes-256-cbc -md sha512 -e -a -pass pass:${ENCRYPTION_PASSWORD}
        echo '-'
        echo $GPG_KEY | openssl aes-256-cbc -md sha512 -e -a -pass pass:${ENCRYPTION_PASSWORD}


    - name: Test
      run: sbt test